title = "Athena Lunch Party"


[[dishes]]
course = "Main Course"
recipe = "sous-vide-prime-rib"

[[dishes]]
course = "Main Course"
recipe = "indoor-clambake"

[[dishes]]
course = "Main Course"
name = "poultry (roast chicken or duck confit)"

[[dishes]]
course = "Side Course"
recipe = "salmon-ceviche-artichoke-leche-de-tigre"

[[dishes]]
course = "Side Course"
name = "Shrimp Cocktail"

[[dishes]]
course = "Side Course"
name = "Soft-Poached Egg with Yogurt and Sun-Roasted Tomato Pesto"

[[dishes]]
course = "Accompaniments"
name = "Pommes Purée"

[[dishes]]
course = "Accompaniments"
name = "roast corn"

[[dishes]]
course = "Accompaniments"
name = "Salad"

[[dishes]]
course = "Accompaniments"
name = "Breads"


[[dishes]]
course = "Dessert"
recipe = "sous-vide-creme-brulee"

[[dishes]]
course = "Dessert"
name = "Ice Cream"


[[dishes]]
course = "Dessert"
recipe = "fruit-and-chocolate"
