title = "Athena Lunch Party"


[[dishes]]
course = "Main Course"
name = "Prime Rib Roast"
recipe = "sous-vide-prime-rib"
description = "No-bullshit prime rib cooked medium-rare from edge to edge."

[[dishes]]
course = "Main Course"
recipe = "indoor-clambake"
description = "A stockpot clambake with lobster, shellfish, sausage, potatoes, and corn."

[[dishes]]
course = "Main Course"
name = "Roast Chicken"
description = "Oven-roasted whole chicken with traditional Latin spices."
recipe = "peruvian-roast-chicken"

[[dishes]]
course = "Side Course"
recipe = "salmon-ceviche-artichoke-leche-de-tigre"

[[dishes]]
course = "Side Course"
recipe = "shrimp-cocktail"
name = "Shrimp Cocktail"


[[dishes]]
course = "Side Course"
name = "Soft-Poached Egg with Yogurt and Sun-Roasted Tomato Pesto"

[[dishes]]
course = "Accompaniments"
name = "Pommes Purée"
recipe = "thomas-keller-pommes-puree"
description = "Potato, cream, and butter—nuff said."


[[dishes]]
course = "Accompaniments"
name = "Salad"
description = "Whatever is in season and sold at the farmers' market."

[[dishes]]
course = "Accompaniments"
name = "Breads"
description = "Rosalind sourdough loaf with French butter."


[[dishes]]
course = "Dessert"
recipe = "sous-vide-creme-brulee"

[[dishes]]
course = "Dessert"
name = "Ice Cream"
description = "Alec's vanilla and brown-butter peach-cobbler ice cream."

[[dishes]]
course = "Dessert"
name = "Silvanas"
description = "From 'House of Silvanas' in Daly City"

[[dishes]]
course = "Dessert"
recipe = "fruit-and-chocolate"
description = "... and love"


[[dishes]]
course = "Alcoholic Menu"
name = "Champagne"
description = "From France, as it should be."

[[dishes]]
course = "Alcoholic Menu"
name = "Wine and Beer"
description = "From Costco, as it should be."


[[dishes]]
course = "Alcoholic Menu"
name = "Mezcal Negroni"
description = "Mucho fancy."

[[dishes]]
course = "Alcoholic Menu"
name = "Frozen Aperol Spritz"

[[dishes]]
course = "Non-Alcoholic Menu"
name = "Sparkling Water"
description = "Topo Chico and S.Pellegrino."

[[dishes]]
course = "Non-Alcoholic Menu"
name = "Soda"
description = "An assortment of sodas."

[[dishes]]
course = "Non-Alcoholic Menu"
name = "Coffee & Tea"
